- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.2
  hooks:
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: flake8
      args:
          - --exclude=__init__.py,docs/conf.py
    - id: autopep8-wrapper
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: git://github.com/asottile/reorder_python_imports
  sha: v0.3.5
  hooks:
    - id: reorder-python-imports
      language_version: 'python2.7'
