- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 'v0.4.2'
  hooks:
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: flake8
      exclude: __init__.py,docs/conf.py
    - id: name-tests-test
    - id: autopep8-wrapper
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: git://github.com/asottile/reorder_python_imports
  sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
  hooks:
    - id: reorder-python-imports
      language_version: 'python2.7'
