sudo: required
services:
- docker
language: python
before_install:
- pip install poetry
- poetry install -v
script:
- make test
deploy:
  before_deploy:
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
    - poetry build
  deploy:
    provider: script
    script: poetry publish
  on:
    tags: true
env:
  global:
  - secure: p5Cm+cSzWB5MsCSbl9p+NHT3OrxBGhhtXJxVoYh2twrYbVOZiUVqmd1YIzMJ/kI3Vq7hDN7AX1XKQcCX7URlf/Ms6Xb66I2jsmeX/pzMkyT+SonjeDR4AHif1Spa5uoS+kn5HKKprgfd5sAgJL7G6ML34wvNsemM4MukbucpdVPLh+kIXaN1mIhBVda3i48rHO3A08GCZbd4rSaTK/eHSXgo7kkfWSSMNeGhBW61xZeR63wo4EB5Ih84XdCObOV1QHMISnF8NuqEvfmPz6cxJuRiSMarCqxdQ3jZWSaNORhHUPyrJUDeLcU9DN24IvF5BPomTneCwgGKmwgZfVPwVXBGKKK7FaX0K5PpshA/qZpi62LRGPuScsn27NEiGIezsfqFnRRvn+3Pgs1/fhuFsFVMcWqORhprwrCr1SEM7yz5pFQTJTnCEcfUaRe29EHMVPD+dJ0FlSykxfbFhu4dcKsR6yCZXsoiepKMYPb0MLO0qyQLwjKhMhd+NLlw/Jl0dNF761MRX4QPuC4ecRBCmHwajgo+mc5VLdZp0VQwN938HWe1lughbk34lLDvRP1uHkWpvB6U2F1JYmwUYAkhgVlbjgK6rQIMpHen594XwPQcXqPlechMrA3q86A/JewwcYYmn35d5yHxRXhWLd/0CktryxysOZ9oldhgNgPkysA=
  - secure: KE27UMwkm3L7uCLO3fR7JEfBULAfd2/lfwxjmGXZAD4WTASlraKByYj6hq9Pzj3E6tu1yemCWfZWr52pKLg1iFO7+fNOP52spNayjK4gYDrkp3O2bTTQeI5o6mClYGssGK1CsND+PyXcpLqfgj0QmC+y1U9zOsJhE9zB0/4a4QY9P/yNuehaKfOrCdeNpWa4cWPwHUMhwHBZxwTA5AUe8jCmv4tBkpsmTwNvu7PV0pdKo/s9uth7ggVBt6VDap7dSTwNEQiG7s85wf7l4vLIuQ0hmy5EvAyLa6/HED67b2yAN6Yv9kXCmDclSQxQmwN3jrjGEIv/kC5tJ6FqGSFtL1suRGVPSZLRMBB+vERMYHEDaUZ3G6Kayf6TGfvWE++WaqrruqyV6mQcsoTP9X/7SiOQtYso3mRtdMmx7HySc+hGPZOsDkACipwTy1lfvM6Y0rLXreidFBeK/unV2P5lGFsjP8ow04MgJ8F21BvFq+HYVcfwzRbE6VQnJWdN2lRuS3hKOHZ0Y5t4gBe8qGFhIwSsN/rIMdzeg4dzKaVKAKSK9qwOUIVC9mAl/V1ZfN7CpC8biYEY1XlhmVV+KECR9SGapb2laLftDYfz3R4833nOCGjgyFB9DxG5Rc9HfGMVqdYaDURbblSRb5vjVMWZLIvfNttrLmjLJI+j5T2dfQM=
