sudo: required
services:
- docker
language: python
before_install:
- pip install -r requirements-dev.txt
script:
- make test
deploy:
  provider: pypi
  user: cmehay
  password:
    secure: P3Xz/ZKIwY5AxFKqzf86gwXRCThKzsXK/D7tKXGH4yETI9JZuh4EyWHI0ozNXzNSThnwLmDhlhaTjq+hVtMEpfBF3iEXQ9svlXHDW70+PXkEp81Zkm2yNBKM0uZB1DJDMXFKbVaBIKiFXHocUmOEGwwPxmPe+6QXNFUuNNTlb/iBnpSATyhvFRdgpVT327DOsco7fzFytAdi9yA4y11fTTo/mQlTaLcWqKRrUFNeP50LLKXB7a/YSC2HNYy2op6linkrCgx+kLj2FxTuWBh5jxAk97t146h7VaoYh4FhSjZ2gssbKQkU0CUD1SjELWHKrsquHI6qJJyGiIUd4GUmoNMv4GWvja9n0KjP2Dc+M5qBkHkBBpe7DIzltil5RH91Fq3m2SLeCFmNg7nYHwh5Ng3dr5gHwo9L5EmSaixFYeax2jxaInPpUfW7pIxCiRFoIFBp63w2TGg3MGRnWOZYmozzJVRHmx9wE5zgX19Eb1Tm1MA9q8Pk5xXs0US0AGnIZ/yKBLAj4pbhN57c29zfcSbzpNM/Yq69RxYBCrmq484oKDU7DhXZXgsnErTufDYJ3/o4qNjiOmXMwxLn8zmJAhJ63JGQNNz+XHGOvwNq+OI2g6SnI3f5EU9UxiZ0n3un8M5YYiG67b6KdSu+dsYKMCV3Tiv0zjJbasVr6TzXHts=
  on:
    tags: true
