# Testing with python 2

FROM python:2

RUN pip install pytest twiggy six pyyaml jinja2

ENV PYTHONPATH /opt/pyentrypoint/

ADD pyentrypoint /opt/pyentrypoint/
ADD tests /opt/pyentrypoint/tests
ADD tests/entrypoint-config.yml /opt/pyentrypoint/

ADD tests/test_template /tmp/tests

WORKDIR /opt/pyentrypoint/

CMD ["py.test", "-s", "."]
