testpython3:
    build: .
    dockerfile: Dockerfile-test.py3
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ

testpython3.8:
    build: .
    dockerfile: Dockerfile-test.py3.8
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ

testpython3.9:
    build: .
    dockerfile: Dockerfile-test.py3.9
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ


testpython3.10:
    build: .
    dockerfile: Dockerfile-test.py3.10
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ


test1:
    image: busybox
    command: sleep 30
    expose:
        - 800
        - 8001/udp
    environment:
        FOO: bar

test2:
    image: busybox
    command: sleep 30
    expose:
        - 800/udp
        - 8001

test3:
    image: busybox
    command: sleep 30
    environment:
        FOO: bar

test4:
    image: busybox
    command: sleep 30
