# Testing with python 2

FROM python:2

RUN pip install pytest twiggy six pyyaml

ADD python-entrypoint /opt/python-entrypoint/
ADD tests/entrypoint-config.yml /opt/python-entrypoint/

WORKDIR /opt/python-entrypoint/

CMD ["py.test", "-s", "."]
