# Testing with python 2

FROM python:2

RUN pip install pytest twiggy six pyyaml jinja2

ENV PYTHONPATH /opt/pyentrypoint/

ADD pyentrypoint /opt/pyentrypoint/
ADD tests /opt/

ADD tests/test_template.yml.tpl /tmp/test_template.yml

WORKDIR /opt/

CMD ["py.test", "-s", "."]
