testpython3:
    build: .
    dockerfile: Dockerfile.py3
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ

testpython2:
    build: .
    dockerfile: Dockerfile.py2
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    extends:
        file: common.yml
        service: environ

testpython3_debug:
    build: .
    dockerfile: Dockerfile.py3
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    command: ["py.test", "--verbose", "-s", "-rw", "."]
    extends:
        file: common.yml
        service: environ

testpython2_debug:
    build: .
    dockerfile: Dockerfile.py2
    volumes:
        - ./pyentrypoint:/opt/pyentrypoint:ro
        - ./tests:/opt/tests
    links:
        - test1
        - test2
        - test3
        - test4
    command: ["py.test", "--verbose", "-s", "-rw", "."]
    extends:
        file: common.yml
        service: environ

test1:
    image: busybox
    command: sleep 30
    expose:
        - 800
        - 8001/udp
    environment:
        FOO: bar

test2:
    image: busybox
    command: sleep 30
    expose:
        - 800/udp
        - 8001

test3:
    image: busybox
    command: sleep 30
    environment:
        FOO: bar

test4:
    image: busybox
    command: sleep 30
