FROM python:3.9

ENV POETRY_VIRTUALENVS_CREATE=false

ADD . /usr/local/src/

RUN cd /usr/local/src/ && \
    pip install --upgrade pip poetry && \
    poetry install --no-dev

ONBUILD ADD entrypoint-config.yml .

ENTRYPOINT ["pyentrypoint"]
